### ISSUE TITLE
IE and Firefox compatible?

### ISSUE THREAD

**Issue by minijag** [alizahid/jquery-sliding-menu#5]
Hope you're still around, and supporting this project.  I'm having issues with the placement of my carat in the sliding menu on IE and Firefox.  I've narrowed the problem down to this line 

"menu.empty().addClass('sliding-menu');"

In chrome the css attribute 'boxSizing' is no longer exists, because of empty().

However, in Firefox and IE, the boxSizing attribute still exists.

Maybe it's because of the modularization on my own that could be the problem.  I was wondering if you have this compatibility problem on your projects.  As it will determine how I approach the solution.

**Comment by alizahid** [comment]
@minijag Hi. Could you put up a screenshot so I could see what you're seeing? I primarily use Chrome and Safari, and I've never had the issue you're having right now. Will try Firefox and see what's up.

**Comment by minijag** [comment]
This is two images combined into one, if it wasn't clear.

![aphoto](https://cloud.githubusercontent.com/assets/2559930/6375300/0c06512e-bccb-11e4-8ab4-c56ebf8d9360.jpg)

**Comment by alizahid** [comment]
@minijag This seems like a styling issue. Could possibly be because of your added CSS for the icons on the left, or CSS reset, or some global CSS.

Why don't you try inspecting those icons in Chrome and see what's affecting their styling.

I tried it in Firefox last night, I was unable to reproduce your issue.

**Comment by minijag** [comment]
Ah, interesting.  No worries.

**Comment by alizahid** [comment]
@minijag Were you able to fix this?

**Comment by minijag** [comment]
Yes, I removed empty(), like I mentioned in the first comment.  It doesnt duplicate children because the  elements are built from the same ones you emptied, and you can't have duplicate elements in your dom.  So if they exist, they just get moved when you append them again.  It's a little sloppy, but I dont think it will ever cause problems.   Thanks for your help, nice library

**Comment by alizahid** [comment]
I'm glad you got that sorted.

Thank you! I plan on rewriting it soon, to fix other issues, and make it more "next-gen" and optimized, etc.
